# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ed0A6vdJPfvWnHyD3eymDEXH4nw0Aay1
"""

# description : ce programe prédire fonctionnement de tour

#import the libraries 
import numpy as np
import pandas as pd
import seaborn as sns

# load the data
from google.colab import files 
uploaded = files.upload()

# store the data into a data frame 
df = pd.read_excel('DATA Tour EVS.xlsx')
# print the first 10 rows of data
df.head(10)

#Get the number of rows and cols
df.shape

#Get the colum data types 
df.dtypes

#get a count of the empthy values for each column 
df.isna().sum()

# check for any missing/null values in the data 
df.isnull().values.any()

#view some statistics 
df.describe()

#print all of the data types and their unique values 
for column in df.columns :
  if df[column].dtype == object:
    print( str (column) +':'+ str (df[column]))
    print(df[column].value_counts())
    print('______________________________')

#show the depression between "chambre de melange" and c4
import matplotlib.pyplot as plt
plt.subplots(figsize=(50,10))
sns.countplot(x='Dp chambre mélange/C4', data= df)